name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Setup
    steps:
      - uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    
    steps:
    - uses: murillomamud/action-deploy-cap@master
      with:
        cf_api: https://api.cf.us10-001.hana.ondemand.com
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        command: push helloworld