name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install MTA Build Tool
      run: npm install -g mbt
    - name: Disable package-lock.json
      run: npm config set package-lock false
    - name: Build MTA
      run: mbt build -p cf
    - name: Upload Artifact
      uses: actions/upload-artifact@master	
      with:	
        name: mta
        path: ./mta_archives/helloworld_1.0.0.mtar      

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    
    steps:

    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: mta
        path: ./

    - uses: murillomamud/action-deploy-cap@master
      with:
        cf_api: https://api.cf.us10-001.hana.ondemand.com
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        command: deploy ./helloworld_1.0.0.mtar -f